baseURL: https://stonedtolife.com/
copyright: Renee Schulz
enableRobotsTXT: true
googleAnalytics: G-FLXJ3MWGGM
languageCode: en-us
theme: PaperMod
title: Stoned to Life

menu:
  main:
    - identifier: 'about'
      name: 'About'
      url: '/about'
      weight: 10
